name = "Du"
type = "TDesignSensorArrayProtocol"
description = "protocol for measuring fields with the cube."
targetScanner = "CalibCube"
sequence = "DummySequence"

controlTx = false
fgFrames = 1
bgFrames = 1